export const ServicesPages = [
  {
    id: "seguro-de-automoveis",
    title: "Seguro de Automóveis",
    subtitle: "Seu primeiro passo",
    banner: "../../images/banners/automoveis.jpg",
    grid: [[1], [1, 1], [1]],
    types: ["text_simple", "topic_bold", "topic_bold", "contact_button"],
    content: [
      [
        "O seguro para automóvel tem o objetivo de cobrir danos parciais ou perda total causados ao veículo segurado. Além dos prejuízos de reparo do veículo ou da indenização, a apólice cobre as despesas com o socorro e salvamento do veículo.",
      ],
      {
        title: "Coberturas básicas:",
        itens: [
          "Colisão, incêndio e roubo/furto",
          "Danos a terceiros",
          "Danos corporais aos passageiros",
        ],
      },
      {
        title: "Coberturas adicionais:",
        itens: [
          "Reparo ou substituição de vidros, lanternas, faróis e retrovisores",
          "Aluguel de carro reserva",
          "Isenção de franquia",
          "Assistência 24hs",
        ],
      },
      "contact_button",
    ],
    formGrid: [2, 2, 2, 2, 1],
    form: [
      {
        name: "first-name",
        type: "text",
        label: "Primeiro nome",
        required: true,
      },
      {
        name: "last-name",
        type: "text",
        label: "Sobrenome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "type",
        type: "select",
        label: "Tipo do veículo",
        options: [
          "Selecione o tipo do veículo",
          "Carro",
          "Caminhão",
          "Caminhonete",
          "Van",
        ],
        required: true,
      },
      {
        name: "plate",
        type: "text",
        label: "Placa do veículo",
        required: true,
        validation: "^[A-Z]{3}-\\d{4}$",
      },
      {
        name: "year",
        type: "number",
        label: "Ano do veículo",
        required: true,
        validation: "^\\d{4}$",
      },
      {
        name: "model",
        type: "text",
        label: "Modelo do veículo",
        required: true,
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "seguro-de-moto",
    title: "Seguro de Moto",
    subtitle: "Proteção completa",
    banner: "../../images/banners/moto.jpg",
    grid: [[1], [1], [1, 1], [1], [1]],
    types: [
      "text_bold",
      "text_bold",
      "text_bold",
      "image_rectangle",
      "text_bold",
      "contact_button",
    ],
    content: [
      {
        title: "Proteção contra roubo de moto ou furto:",
        text: [
          "Em casos de roubo ou furto, você pode contar com indenização de até 100% da tabela FIPE onde não há recuperação da motocicleta. Você conta também com assistência 24 horas, para ficar livre de qualquer situação que venha a acontecer no dia a dia.",
        ],
      },
      {
        title: "Serviços de assistência 24 horas:",
        text: [
          "Oferece serviços de assistência 24 horas em caso de acidentes, roubo ou furto de moto, com atendimento disponível para todo o território brasileiro.",
        ],
      },
      {
        title: "Serviço de chaveiro:",
        text: [
          "Disponível nos casos em que haja impossibilidade, perda ou esquecimento da chave. Um chaveiro será enviado até o local onde está sua motocicleta, para poder te ajudar.",
        ],
      },
      "../../images/services/moto.jpg",
      {
        title: "Guincho e reboque:",
        text: [
          "O reboque de moto é uma assistência que pode ser contratada em seguros de moto, e que é acionada em caso de pane, acidente ou furto.",
        ],
      },
      "contact_button",
    ],
    formGrid: [2, 2, 2, 1, 1],
    form: [
      {
        name: "first-name",
        type: "text",
        label: "Primeiro nome",
        required: true,
      },
      {
        name: "last-name",
        type: "text",
        label: "Sobrenome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "plate",
        type: "text",
        label: "Placa do veículo",
        required: true,
        validation: "^[A-Z]{3}-\\d{4}$",
      },
      {
        name: "year",
        type: "number",
        label: "Ano do veículo",
        required: true,
        validation: "^\\d{4}$",
      },
      {
        name: "model",
        type: "text",
        label: "Modelo do veículo",
        required: true,
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "seguro-de-bike",
    title: "Seguro de Bike",
    subtitle: "Proteção para sua bike",
    banner: "../../images/banners/bike.jpg",
    grid: [[1], [1, 1], [1], [1]],
    types: [
      "text_simple",
      "topic_bold",
      "topic_bold",
      "text_simple",
      "contact_button",
    ],
    content: [
      [
        "Pedalar é uma excelente forma de locomoção, lazer e prática esportiva, mas imprevistos podem acontecer. O seguro de bicicleta é uma solução essencial para garantir mais segurança e tranquilidade, oferecendo proteção contra diversos riscos. Assim como os seguros para automóveis e motos, ele cobre situações como roubo, furto qualificado, danos acidentais e responsabilidade civil, evitando prejuízos financeiros ao ciclista.",
      ],
      {
        title: "Coberturas básicas:",
        itens: [
          "Colisão",
          "Roubo",
          "Furto",
          "Danos a terceiros",
          "Entre outros",
        ],
      },
      {
        title: "Coberturas opcionais:",
        itens: [
          "Responsabilidade civil",
          "Danos à bicicleta",
          "Assistência 24 horas",
          "Transporte",
          "Extensão para transporte",
          "Internacional",
          "Reboque",
        ],
      },
      [
        "Contratar um seguro para bicicleta é investir na sua segurança e evitar preocupações com imprevistos. Seja para uso urbano, competições ou lazer, essa proteção garante que você pedale com mais liberdade e confiança.",
      ],
      "contact_button",
    ],
    formGrid: [2, 1, 1, 1],
    form: [
      {
        name: "first-name",
        type: "text",
        label: "Primeiro nome",
        required: true,
      },
      {
        name: "last-name",
        type: "text",
        label: "Sobrenome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "seguro-de-vida",
    title: "Seguro de Vida",
    subtitle: "Proteção para você e sua família",
    banner: "../../images/banners/vida.jpg",
    grid: [[1], [2, 1], [1]],
    types: [
      "text_simple",
      "topic_bold",
      "topic_bold",
      "image_rectangle_2",
      "contact_button",
    ],
    content: [
      [
        "O seguro de vida é um contrato que garante uma indenização em dinheiro à família do segurado em caso de morte, acidente, invalidez ou outras situações.",
        "A indenização pode ser utilizada para cobrir despesas como custos com funeral, assistência médica, contas do dia a dia e outras necessidades financeiras. Além disso, o segurado tem a liberdade de escolher os beneficiários, ou seja, as pessoas que receberão o valor segurado. Caso não haja uma designação específica, a indenização será destinada ao cônjuge e/ou herdeiros legais.",
        "Proteja quem você ama! Solicite uma cotação e descubra as melhores opções para o seu perfil.",
      ],
      {
        title: "Coberturas básicas:",
        itens: ["Morte natural", "Morte acidental"],
      },
      {
        title: "Coberturas adicionais:",
        itens: [
          "Invalidez permanente total ou parcial por acidente",
          "Diária por incapacidade temporária (DIT)",
          "Doenças graves",
          "Despesas médico-hospitalares e odontológicas",
          "Assistência funeral individual ou familiar",
          "Majoração para médicos e dentistas ",
          "Outras",
        ],
      },
      "../../images/services/vida.jpg",
      "contact_button",
    ],
    formGrid: [2, 1, 1, 1],
    form: [
      {
        name: "first-name",
        type: "text",
        label: "Primeiro nome",
        required: true,
      },
      {
        name: "last-name",
        type: "text",
        label: "Sobrenome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "seguro-saude",
    title: "Seguro Saúde",
    subtitle: "Cuidado e proteção",
    banner: "../../images/banners/saude.jpg",
    grid: [[1], [1, 1], [1], [1]],
    types: [
      "text_simple",
      "topic_simple",
      "topic_simple",
      "text_simple",
      "contact_button",
    ],
    content: [
      [
        "O seguro saúde é um serviço que garante assistência médica, hospitalar e terapêutica, proporcionando mais segurança e tranquilidade para o segurado. Ao contratar um seguro, o beneficiário paga uma mensalidade, chamada de prêmio, e tem acesso a uma rede credenciada de profissionais e instituições de saúde.",
      ],
      {
        title:
          "Esse tipo de seguro pode ser contratado de diferentes formas, de acordo com as necessidades de cada pessoa ou empresa:",
        itens: [
          "Individual",
          "Familiar",
          "Coletivo por adesão",
          "Coletivo empresarial",
        ],
      },
      {
        title: "O seguro saúde pode oferecer os seguintes benefícios: ",
        itens: [
          "Cobertura para despesas médicas e hospitalares",
          "Assistência médica 24 horas por telefone",
          "Programas de prevenção de saúde",
          "Descontos em medicamentos",
          "Coleta domiciliar de exames",
          "Psicólogos online",
        ],
      },
      [
        "Ter um seguro saúde é um investimento essencial no bem-estar e na qualidade de vida, garantindo acesso a serviços médicos de qualidade sempre que necessário.",
      ],
      "contact_button",
    ],
    formGrid: [2, 2, 1, 1],
    form: [
      {
        name: "first-name",
        type: "text",
        label: "Primeiro nome",
        required: true,
      },
      {
        name: "last-name",
        type: "text",
        label: "Sobrenome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "quantity",
        type: "number",
        label: "Quantidade de pessoas",
        required: true,
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "previdencia",
    title: "Previdência",
    subtitle: "Planeje o futuro",
    banner: "../../images/banners/previdencia.jpg",
    grid: [[1], [1], [1], [1, 1], [1], [1, 1], [1]],
    types: [
      "text_simple",
      "title",
      "text_bold",
      "text_bold",
      "image_rectangle_2",
      "text_bold",
      "topic_bold",
      "topic_bold",
      "contact_button",
    ],
    content: [
      [
        "Comece a planejar agora mesmo um futuro com mais segurança e proteção financeira para você e sua família. A Previdência Privada oferece planos personalizados que permitem a complementação de sua renda de aposentadoria.",
      ],
      "Planos disponíveis",
      {
        title: "VGBL (Vida Gerador de Benefício Livre)",
        text: [
          "Ideal para quem utiliza o modelo simplificado da declaração de Imposto de Renda, no qual a tributação incide somente sobre os rendimentos do plano no momento do resgate e/ou no recebimento sob a forma de renda.",
        ],
      },
      {
        title: "PGBL (Plano Gerador de Benefício Livre)",
        text: [
          "Criado para quem declara o Imposto de Renda pelo modelo completo. As contribuições pagas pelo participante terão direito ao incentivo fiscal de dedução da base de cálculo do IR ou na declaração anual, limitado a 12% da sua renda bruta anual tributável, reduzindo o valor a ser pago ou aumentando o valor da sua restituição.",
          "O PGBL é uma boa opção para contribuintes da Previdência Social, seja no setor público ou privado.",
        ],
      },
      "../../images/services/previdencia.jpg",
      {
        title: "Previdência Infantil (Prever)",
        text: [
          "A previdência privada infantil é um plano de investimento que visa garantir a segurança financeira de uma criança. É uma forma de poupar dinheiro e acumular patrimônio para o futuro.",
          "A previdência privada infantil pode ser contratada por qualquer adulto, como pais, avós, tios, padrinhos, madrinhas, ou até mesmo pessoas sem vínculo familiar.",
        ],
      },
      {
        title: "Vantagens da previdência privada infantil:",
        itens: [
          "Pode ser uma herança financeira para as gerações futuras.",
          "Pode ser uma forma de proteção no caso do falecimento do titular da conta.",
          "Pode oferecer rendimentos melhores do que a poupança.",
          "Pode ser um complemento à previdência social.",
        ],
      },
      {
        title: "Como funciona a previdência privada?",
        itens: [
          "O responsável legal do menor contrata o plano.",
          "O dinheiro é aplicado no mercado financeiro.",
          "O montante cresce ao longo do tempo, devido aos juros.",
          "O resgate pode ser planejado para uma data específica, como a maioridade da criança.",
        ],
      },
      "contact_button",
    ],
    formGrid: [2, 1, 1, 1],
    form: [
      {
        name: "first-name",
        type: "text",
        label: "Primeiro nome",
        required: true,
      },
      {
        name: "last-name",
        type: "text",
        label: "Sobrenome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "seguro-residencial",
    title: "Seguro Residencial",
    subtitle: "Proteção para sua casa",
    banner: "../../images/banners/residencial.jpg",
    grid: [[1], [2, 1], [1]],
    types: [
      "text_simple",
      "topic_bold",
      "image_rectangle",
      "topic_bold",
      "contact_button",
    ],
    content: [
      [
        "O seguro residencial oferece cobertura contra danos materiais causados por incêndios, raios e explosões, garantindo mais segurança e tranquilidade para o proprietário. Além das coberturas básicas, é possível incluir proteções adicionais para ampliar a segurança do imóvel e dos bens.",
      ],
      {
        title: "Coberturas básicas:",
        itens: ["Incêndio.", "Explosão.", "Fumaça."],
      },
      "../../images/services/residencial.jpg",
      {
        title: "Coberturas adicionais:",
        itens: [
          "Danos morais.",
          "Subtração de bicicletas.",
          "Desmoronamento.",
          "Vazamento de tubulações.",
          "Danos elétricos.",
          "Impacto de veículos.",
          "Vendaval, furacão, ciclone, tornado e queda de granizo.",
          "Quebra de vidros.",
          "Responsabilidade civil familiar.",
          "Subtração de bens.",
          "Escritório em residência.",
          "Perda ou pagamento de aluguel.",
        ],
      },
      "contact_button",
    ],
    formGrid: [2, 1, 1, 1],
    form: [
      {
        name: "first-name",
        type: "text",
        label: "Primeiro nome",
        required: true,
      },
      {
        name: "last-name",
        type: "text",
        label: "Sobrenome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "consorcio",
    title: "Consórcio",
    subtitle: "Realize seus sonhos",
    banner: "../../images/banners/consorcio.jpg",
    grid: [[1], [1, 1], [1], [1], [1]],
    types: [
      "text_bold",
      "text_bold",
      "text_bold",
      "text_bold",
      "text_bold",
      "contact_button",
    ],
    content: [
      {
        title: "O que é o Consórcio?",
        text: [
          "Consórcio é uma modalidade de compra em que um grupo de pessoas se une para adquirir um bem ou serviço. Os participantes do consórcio são chamados <b>consorciados</b>.",
        ],
      },
      {
        title: "Como Funciona:",
        text: [
          "Os consorciados pagam parcelas mensais, que formam um fundo comum.",
          "Esse fundo é utilizado para viabilizar a compra do bem desejado, como imóveis, veículos, caminhões, tratores ou motos.",
          "Durante o período do consórcio, todos os consorciados são contemplados, seja por sorteio ou por meio de lance.",
        ],
      },
      {
        title: "Vantagens:",
        text: [
          "O consórcio é uma das soluções mais acessíveis e vantajosas para conquistar bens de alto valor, como uma casa nova ou equipamentos essenciais.",
          "Oferece flexibilidade, juros zero e parcelas que cabem no seu bolso, tornando o planejamento financeiro mais tranquilo.",
          "É uma forma segura e planejada de adquirir um bem, ideal para quem não tem pressa e valoriza segurança e organização.",
        ],
      },
      {
        title: "Consórcios de Automóveis, Imóveis, Caminhões, Tratores e Motos",
        text: [
          "O consórcio é uma excelente alternativa para quem deseja realizar uma compra importante de forma planejada e sem comprometer seu orçamento.",
          "Ideal para quem prioriza segurança, tranquilidade e um bom planejamento financeiro.",
        ],
      },
      {
        title: "Administradora de Consórcios",
        text: [
          "A formação dos grupos de consórcio é realizada por uma Administradora de Consórcios, devidamente autorizada e fiscalizada pelo Banco Central do Brasil, garantindo transparência e confiança no processo.",
        ],
      },
      "contact_button",
    ],
    formGrid: [2, 1, 1, 1],
    form: [
      {
        name: "first-name",
        type: "text",
        label: "Primeiro nome",
        required: true,
      },
      {
        name: "last-name",
        type: "text",
        label: "Sobrenome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "equipamentos-portateis",
    title: "Equipamentos Portáteis",
    subtitle: "Proteção para seus aparelhos",
    banner: "../../images/banners/equipamentos-portateis.jpg",
    grid: [[1], [1, 1], [1], [1], [1]],
    types: [
      "text_simple",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "contact_button",
    ],
    content: [
      [
        "Você já pensou em contratar um seguro para seu notebook, smartphone, iPhone etc., iPad ou outros modelos de tablets, câmera fotográficas e filmadoras e assim garantir a reposição do equipamento em caso de danos ou roubo?",
        "Para você que se locomove com frequência e não quer correr o risco de ficar sem sua ferramenta de trabalho e comunicação, desenvolvemos o Seguro para Equipamentos Portáteis, que garante a reposição do seu equipamento no caso de incêndio, raio, explosão e impacto de veículos terrestres e aeronaves. Você também pode contratar a cobertura opcional para subtração de bens e danos elétricos, além de garantia internacional.",
      ],
      {
        title: "Produtos seguráveis:",
        itens: [
          "Smartphones",
          "Smartwatches",
          "Tablets",
          "Notebooks",
          "Câmeras fotográficas e filmadoras",
        ],
      },
      {
        title: "Principais coberturas:",
        itens: [
          "Caso de acidentes",
          "Caso de incêndio",
          "Queda de raio",
          "Dano na tentativa de roubo",
          "Impacto de veículos",
        ],
      },
      {
        title: "Para equipamentos adquiridos fora do Brasil:",
        itens: [
          "Quando adquirido no exterior, a cotação do equipamento deve ser realizada em moeda nacional e informada no campo <b>Valor da Nota Fiscal</b>.",
          "Em caso de documentos em língua estrangeira, diferente do inglês, será necessário documento com as especificações da marca, modelo e número de série.",
        ],
      },
      {
        title:
          "Para equipamentos em que a Nota Fiscal está em nome de terceiros:",
        itens: [
          "Em caso de Nota Fiscal com nome diferente do segurado, será exigida carta de doação ou documento que comprove a aquisição.",
        ],
      },
      "contact_button",
    ],
    formGrid: [2, 2, 2, 1],
    form: [
      {
        name: "first-name",
        type: "text",
        label: "Primeiro nome",
        required: true,
      },
      {
        name: "last-name",
        type: "text",
        label: "Sobrenome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "type",
        type: "select",
        label: "Tipo de equipamento",
        options: [
          "Selecione o tipo de equipamento",
          "Smartphone",
          "Smartwatch",
          "Tablet",
          "Notebook",
          "Câmera fotográfica",
          "Filmadora",
          "Outro",
        ],
        required: true,
      },
      {
        name: "value",
        type: "text",
        label: "Valor do equipamento",
        required: true,
        validation: "R$ \\d{1,3}(\\.\\d{3})*(,\\d{2})?",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "seguro-de-condominio",
    title: "Seguro de Condomínio",
    subtitle: "Proteção para seu patrimônio",
    banner: "../../images/banners/condominio.jpg",
    grid: [[1], [2, 1], [1]],
    types: [
      "text_simple",
      "topic_bold",
      "image_rectangle_2",
      "topic_bold",
      "contact_button",
    ],
    content: [
      [
        "Seguro ideal para condomínios verticais residenciais, comerciais, mistos, de escritórios e/ou consultórios, flats e apart-hotéis, bem como condomínios residenciais horizontais. Com preço acessível e pagamento facilitado, ele oferece inúmeras vantagens.",
        "Ele é um seguro completo, oferece coberturas que protegem o condomínio, o síndico e os colaboradores, além de facilidades e benefícios na contratação, serviços emergenciais gratuitos, preços e condições de pagamentos vantajosos.",
      ],
      {
        title: "Coberturas básicas:",
        itens: ["Incêndio", "Explosão", "Fumaça", "Queda de aeronaves"],
      },
      "../../images/services/condominio.jpg",
      {
        title: "Coberturas adicionais:",
        itens: [
          "Danos morais",
          "Vendaval e impacto de veículos",
          "Responsabilidade civil da guarda de veículos",
          "Vida e acidentes pessoais de funcionários",
          "Portões",
          "Alagamento",
          "Desmoronamento",
          "Chuveiros automáticos (sprinklers)",
          "Tumultos, greves e lockout",
          "Subtração de valores",
          "Despesas fixas",
          "Responsabilidade civil empregador",
          "Danos elétricos",
          "Quebra de vidros",
          "Painéis, anúncios luminosos e letreiros",
          "Subtração de bens do condomínio",
          "Subtração de bens de condôminos (moradores)",
          "Incêndio, fumaça e explosão de conteúdo de apartamentos",
          "Responsabilidade civil condomínio",
          "Responsabilidade civil do síndico",
          "Outros",
        ],
      },
      "contact_button",
    ],
    formGrid: [1, 1, 2, 2, 1, 1],
    form: [
      {
        name: "business-name",
        type: "text",
        label: "Nome do condomínio",
        required: true,
      },
      {
        name: "address",
        type: "text",
        label: "Endereço",
        required: true,
      },
      {
        name: "cep",
        type: "text",
        label: "CEP",
        required: true,
        validation: "^\\d{5}-\\d{3}$",
      },
      {
        name: "number",
        type: "number",
        label: "Número",
        required: true,
      },
      {
        name: "name",
        type: "text",
        label: "Seu nome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "seguro-empresarial",
    title: "Seguro Empresarial",
    subtitle: "Proteção para sua empresa",
    banner: "../../images/banners/empresarial.jpg",
    grid: [[1], [2, 1], [1]],
    types: [
      "text_simple",
      "topic_bold",
      "topic_bold",
      "image_rectangle_2",
      "contact_button",
    ],
    content: [
      [
        "Proteção completa para empresas de todos os tamanhos e segmentos.",
        "O Seguro Empresarial oferece coberturas personalizadas para pequenas, médias e grandes empresas dos setores de comércio, indústria e serviços, garantindo segurança e continuidade para o seu negócio.",
      ],
      {
        title: "Coberturas básicas:",
        itens: ["Incêndio", "Explosão", "Queda de raio"],
      },
      {
        title: "Coberturas adicionais:",
        itens: [
          "Roubo ou furto qualificado",
          "Recomposição de registros e documentos",
          "Quebra de vidros e anúncios luminosos",
          "Danos elétricos",
          "Perda ou pagamento de aluguel",
          "Diárias por interrupção de atividades",
          "Proteção para equipamentos móveis e estacionários",
          "Outras coberturas personalizadas",
        ],
      },
      "../../images/services/empresarial.jpg",
      "contact_button",
    ],
    formGrid: [1, 2, 1, 1],
    form: [
      {
        name: "business-name",
        type: "text",
        label: "Nome da empresa",
        required: true,
      },
      {
        name: "name",
        type: "text",
        label: "Seu nome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "previdencia-empresarial",
    title: "Previdência Empresarial",
    subtitle: "Planeje o futuro da sua empresa",
    banner: "../../images/banners/previdencia-empresarial.jpg",
    grid: [[1], [1], [1, 1], [1], [1]],
    types: [
      "text_simple",
      "title",
      "text_bold",
      "text_bold",
      "text_bold",
      "contact_button",
    ],
    content: [
      [
        "Comece a planejar agora mesmo um futuro com mais segurança e proteção financeira para você e sua família. A Previdência Privada oferece planos personalizados que permitem a complementação de sua renda de aposentadoria.",
      ],
      "Planos disponíveis",
      {
        title: "VGBL (Vida Gerador de Benefício Livre):",
        text: [
          "Ideal para quem utiliza o modelo simplificado da declaração de Imposto de Renda, no qual a tributação incide somente sobre os rendimentos do plano no momento do resgate e/ou no recebimento sob a forma de renda.",
        ],
      },
      {
        title: "PGBL (Plano Gerador de Benefício Livre):",
        text: [
          "Criado para quem declara o Imposto de Renda pelo modelo completo. As contribuições pagas pelo participante terão direito ao incentivo fiscal de dedução da base de cálculo do IR ou na declaração anual, limitado a 12% da sua renda bruta anual tributável, reduzindo o valor a ser pago ou aumentando o valor da sua restituição.",
        ],
      },
      {
        title: "Previdência Infantil (Prever):",
        text: [
          "Presenteie seus filhos com algo que eles vão levar por toda a vida: a realização de seus sonhos!  Você define o valor e o tempo de contribuição e ainda pode desfrutar de vantagens e incentivos fiscais de acordo com o seu modelo de declaração de Imposto de Renda.",
        ],
      },
      "contact_button",
    ],
    formGrid: [1, 2, 1, 1],
    form: [
      {
        name: "business-name",
        type: "text",
        label: "Nome da empresa",
        required: true,
      },
      {
        name: "name",
        type: "text",
        label: "Seu nome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "responsabilidade-civil",
    title: "Responsabilidade Civil",
    subtitle: "Proteção para você e sua empresa",
    banner: "../../images/banners/responsabilidade-civil.jpg",
    grid: [[1], [1], [1]],
    types: ["text_simple", "topic_bold", "contact_button"],
    content: [
      [
        "O produto de Responsabilidade Civil Profissional foi desenvolvido para profissionais de diversas áreas e o seu objetivo é protegê-los diante de reclamações de terceiros decorrentes de alegadas falhas profissionais por erros ou omissões.",
        "As coberturas garantem as perdas associadas à responsabilidade atribuída ao profissional em consequência da sua prestação de serviços, como custos de defesa, indenizações estipuladas em ações judiciais ou arbitrais contra o segurado, bem como valores decorrentes de acordos celebrados com a anuência prévia e por escrito da seguradora. Há também cobertura para danos morais e custos com restituição de imagem, dentre outros.",
      ],
      {
        title: "Conheça as profissões e coberturas disponíveis:",
        itens: [
          "Médicos e outros profissionais da saúde",
          "Advogados e/ou escritórios de advocacia",
          "Engenheiros, arquitetos e/ou escritórios",
          "Designer de interiores e/ou escritório",
          "Contador e/ou escritórios",
          "Administrador e corretor de imóveis, imobiliária e síndico profissional",
          "Corretores de seguros",
          "Agentes de viagem e/ou agências",
          "Certificação digital e/ou escritórios",
          "Empresas e/ou profissionais de mídia",
          "Empresas de tecnologia",
          "Intermediário de jogador de futebol",
          "Notários e registradores",
          "Veterinário",
          "Outros",
        ],
      },
    ],
    formGrid: [1, 2, 1, 1],
    form: [
      {
        name: "business-name",
        type: "text",
        label: "Nome da empresa",
        required: true,
      },
      {
        name: "name",
        type: "text",
        label: "Seu nome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "seguro-de-vida-empresarial",
    title: "Seguro de Vida Empresarial",
    subtitle: "Proteção para seus colaboradores",
    banner: "../../images/banners/vida-empresarial.jpg",
    grid: [[1], [2, 1], [1]],
    types: [
      "text_bold",
      "topic_bold",
      "topic_bold",
      "image_rectangle_2",
      "contact_button",
    ],
    content: [
      {
        title: "Por que contratar o Seguro de Vida Empresarial?",
        text: [
          "Temos planos completos e acessíveis de proteção e assistência aos funcionários, deixando sua empresa preparada para possíveis situações inesperadas. O seguro de vida empresarial proporciona mais tranquilidade aos colaboradores e seus familiares, além de minimizar impactos ocasionados por eventos inesperados como acidentes ou falecimento.",
          "O seguro de vida empresarial pode ser contratado por todos os tipos de empresa, incluindo prestadores de serviço.",
          "Os custos podem ter a participação ou não do colaborador e a empresa poderá deduzir o valor do seguro no Imposto de Renda. Os benefícios podem ser estendidos a cônjuges e filhos.",
        ],
      },
      {
        title: "Coberturas básicas:",
        itens: ["Morte natural", "Morte acidental"],
      },
      {
        title: "Coberturas adicionais:",
        itens: [
          "Invalidez permanente total ou parcial por acidente",
          "Diária por incapacidade temporária (DIT)",
          "Doenças graves",
          "Despesas médico-hospitalares e odontológicas",
          "Assistência funeral individual ou familiar",
          "Majoração para médicos e dentistas ",
          "Outras",
        ],
      },
      "../../images/services/vida-empresarial.jpg",
      "contact_button",
    ],
    formGrid: [1, 2, 1, 1],
    form: [
      {
        name: "business-name",
        type: "text",
        label: "Nome da empresa",
        required: true,
      },
      {
        name: "name",
        type: "text",
        label: "Seu nome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "seguro-auto-frota",
    title: "Seguro Auto Frota",
    subtitle: "Proteção para sua frota",
    banner: "../../images/banners/auto-frota.jpg",
    grid: [[1], [1], [4, 4], [1], [1, 1], [1], [1], [1]],
    types: [
      "text_bold",
      "title",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "title",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "contact_button",
    ],
    content: [
      {
        title: "Por que contratar o Seguro Auto Frota?",
        text: [
          "Com seguro Auto Frota Compacto, você tem coberturas personalizadas que oferecem a proteção ideal para seus veículos e ainda o custo-benefício que você procura.",
        ],
      },
      "Coberturas que protegem você e seus veículos",
      {
        title: "Danos a terceiros",
        itens: [
          "Garante a cobertura de gastos em reparo de danos a bens materiais patrimoniais e danos corporais causados a terceiros em acidentes.",
        ],
      },
      {
        title: "Assistência 24h compacta",
        itens: [
          "Assistência para passageiros e veículos com: guincho 100 km para pane e 2000 km para sinistro, chaveiro, passagens ao destino ou retorno, reaver veículo, hospedagem e outros.",
        ],
      },
      {
        title: "Reposição de 0km por até 6 meses",
        itens: [
          "Garante a reposição do bem, sem nenhum custo para o cliente durante o prazo de 6 meses, desde que estejam nas condições preestabelecidas no contrato.",
        ],
      },
      {
        title: "Danos Morais e Estéticos",
        itens: [
          "Reembolsa a indenização paga a terceiros — em decorrência de danos morais — envolvidos em acidente de trânsito com o veículo segurado, coberto e indenizável devido a um acionamento judicial. Há, também, as opções de 2º risco, ou seja, quando há necessidade de contratar valores excedentes à contratação da mesma cobertura em uma congênere.",
        ],
      },
      {
        title: "Danos Materiais e Corporais a terceiros – Desatrelado",
        itens: [
          "Cobre eventuais danos corporais e/ou patrimoniais de terceiros. Oferece ainda, as opções de 2º risco, quando há necessidade de contratar valores excedentes a contratação da mesma cobertura em uma congênere. Entende-se como desatrelado, a parte do veículo (reboque ou semirreboque) quando desprendida do cavalo mecânico/rebocador.",
        ],
      },
      {
        title: "Danos Materiais e Corporais a terceiros – Garantia única",
        itens: [
          "Cobre eventuais danos corporais e/ou patrimoniais de terceiros na mesma garantia, dando liberdade ao segurado de utilizá-la no evento de sinistro conforme maior necessidade. Entende-se por 2º risco o critério de contratação de valor complementar desta cobertura, em uma congênere.",
        ],
      },
      {
        title: "Carroceria e equipamentos",
        itens: [
          "Cobertura para itens acoplados ao veículo. Exemplo: plataforma, munk, caçamba, entre outros.",
        ],
      },
      {
        title: "Acessório",
        itens: ["Cobertura para som e imagem."],
      },
      "Quais são as cláusulas que podem ser contratadas para sua frota de veículos",
      {
        title: "Vidros:",
        itens: [
          "Cobre a troca ou reparo dos vidros, em caso de quebra ou trincamento de acordo com as condições que foram contratadas no seguro.",
        ],
      },
      {
        title: "Despesas extraordinárias:",
        itens: [
          "Contratação de importância extra limitada aos critérios da seguradora, que será reembolsada ao segurado em momento de sinistro exclusivo de indenização integral.",
        ],
      },
      {
        title: "Extensão de perímetro:",
        itens: [
          "Garante atendimento, exclusivo para o veículo segurado, em caso de sinistro, na Argentina, Paraguai, Uruguai, Chile e Bolívia.",
        ],
      },
      {
        title: "Extensão de cobertura para veículos de rebocados:",
        itens: [
          "Cobre danos materiais ocasionados ao veículo rebocado de terceiros (automotor de via terrestre) em poder do segurado. Cobre danos materiais e/ou corporais a terceiros pelo veículo rebocado durante uma operação de reboque.",
        ],
      },
      "contact_button",
    ],
    formGrid: [1, 2, 1, 1],
    form: [
      {
        name: "business-name",
        type: "text",
        label: "Nome da empresa",
        required: true,
      },
      {
        name: "name",
        type: "text",
        label: "Seu nome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "maquinas-e-equipamentos",
    title: "Máquinas e Equipamentos",
    subtitle: "Proteção para seus bens",
    banner: "../../images/banners/maquinas-equipamentos.jpg",
    grid: [[1], [1, 2]],
    types: ["text_simple", "topic_simple", "image_rectangle", "contact_button"],
    content: [
      [
        "O Seguro para Máquinas e Equipamentos é um produto completo que visa proteger bens de diversas categorias, os amparando contra perdas, roubos e danos materiais (inclusive elétricos). As coberturas abrangem equipamentos de construção civil, ramo industrial, médicos, estéticos, de análises e medição, mobilidade, como cadeira de rodas, além de equipamentos diversos, como monociclos e equipamentos de energia solar (placas solares).",
      ],
      {
        title:
          "Coberturas que podem ser contratadas em complemento à cobertura básica e que oferecem ainda mais segurança e tranquilidade a você:",
        itens: [
          "Danos elétricos.",
          "Içamento, carga e descarga.",
          "Perda e/ou pagamento de aluguel (PI: 6 meses).",
          "Responsabilidade civil máquinas.",
          "Equipamentos próximos à água.",
          "Responsabilidade civil operador.",
          "Furto simples.",
        ],
      },
      "../../images/services/maquinas-equipamentos.jpg",
      "contact_button",
    ],
    formGrid: [1, 2, 1, 1],
    form: [
      {
        name: "business-name",
        type: "text",
        label: "Nome da empresa",
        required: true,
      },
      {
        name: "name",
        type: "text",
        label: "Seu nome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "plano-de-saude-empresarial",
    title: "Plano de Saúde Empresarial",
    subtitle: "Proteção para seus colaboradores",
    banner: "../../images/banners/saude-empresarial.jpg",
    grid: [[1], [1], [1, 1], [1], [1], [1], [1]],
    types: [
      "text_simple",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "topic_bold",
      "text_simple",
      "contact_button",
    ],
    content: [
      [
        "O plano de saúde empresarial é um convênio médico coletivo que empresas oferecem aos seus funcionários. Ele pode ser contratado por empresas de todos os portes, inclusive MEI.",
      ],
      {
        title: "Principais características:",
        itens: [
          "Garante acesso a uma rede médica e hospitalar.",
          "Pode ser pago integralmente pela empresa ou ter uma co-participação financeira dos funcionários.",
          "A empresa negocia melhores condições e preços com a operadora de saúde.",
          "A cobertura e os benefícios podem ser pré-definidos pela empresa ou oferecidos aos funcionários.",
          "É regulamentado pela Agência Nacional de Saúde Suplementar (ANS).",
        ],
      },
      {
        title: "Vantagens do plano de saúde empresarial:",
        itens: [
          "Aumenta a produtividade e melhora a qualidade de vida no trabalho.",
          "Reduz significativamente o número de atestados e afastamentos.",
          "É um dos pilares para a entidade ser bem-vista no mercado.",
        ],
      },
      {
        title: "Quem pode ter acesso ao plano de saúde empresarial?",
        itens: [
          "Funcionários da empresa.",
          "Dependentes dos funcionários.",
          "Trabalhadores temporários.",
          "Colaboradores aposentados.",
        ],
      },
      {
        title:
          "Para escolher o plano de saúde empresarial, é importante considerar os seguintes critérios:",
        itens: [
          "Faixa etária.",
          "Gênero.",
          "Estado civil.",
          "Presença de doenças crônicas.",
        ],
      },
      {
        title: "Conheça as opções:",
        itens: [
          "Ambulatorial, engloba consultas médicas em clínicas e, ou, consultórios, exames e tratamentos ambulatoriais.",
          "Hospitalar, para assistência hospitalar, como pronto-socorro e, ou, internações com possibilidade de serviço obstetra, a depender da empresa.",
          "Segmentado, pode englobar serviços ambulatoriais, internação, cirurgia, tratamentos e obstetrícia.",
          "Odontológico, exclusivo para odontologia com coberturas a depender da negociação.",
          "Teleatendimento: disponibilização de serviços através de plataforma online, atendendo funcionários em diferentes localidades, diminuindo gastos e otimizando tempo, com extensão para atendimento presencial quando necessário.",
        ],
      },
      [
        "Em alguns planos, existe também a possibilidade de desconto na compra de medicamentos, com desconto em folha ou na hora do pagamento.",
      ],
      "contact_button",
    ],
    formGrid: [1, 1, 2, 1, 1],
    form: [
      {
        name: "business-name",
        type: "text",
        label: "Nome da empresa",
        required: true,
      },
      {
        name: "quantity",
        type: "number",
        label: "Quantidade de pessoas",
        required: true,
      },
      {
        name: "name",
        type: "text",
        label: "Seu nome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
  {
    id: "plano-odontologico",
    title: "Plano Odontológico",
    subtitle: "Proteção para sua saúde bucal",
    banner: "../../images/banners/odontologico.jpg",
    grid: [[1], [1], [1], [1]],
    types: ["text_simple", "topic_bold", "topic_bold", "contact_button"],
    content: [
      [
        "Planos empresariais a partir de 3 vidas com ampla rede de dentistas referenciados.",
        "Oferecer benefícios para os funcionários tem se tornado uma estratégia essencial para retenção de talentos. Com o Seguro Odontológico os colaboradores da sua empresa podem exibir um sorriso saudável, com custo acessível.",
      ],
      {
        title: "Vantagens do plano odontológico:",
        itens: [
          "Promove a saúde bucal e o bem-estar dos funcionários.",
          "Oferece preços acessíveis.",
          "Os planos também oferecem uma Rede Referenciada com milhares de consultórios, clínicas. Assim, quando um procedimento coberto é realizado por esta rede, o prestador de serviço recebe diretamente e o segurado não precisa pagar pelo atendimento.",
          "Melhora a qualidade de vida dos funcionários.",
          "Pode ser deduzido do Imposto de Renda, desde que comprovados e dentro dos critérios da legislação tributária.",
        ],
      },
      {
        title: "Como funciona:",
        itens: [
          "A empresa contrata uma operadora odontológica.",
          "O funcionário paga um valor mensal, que varia de acordo com a empresa e os serviços cobertos.",
          "O funcionário pode marcar consultas e procedimentos com profissionais da rede credenciada ou ir a um dentista particular e solicitar o reembolso.",
        ],
      },
      "contact_button",
    ],
    formGrid: [1, 2, 1, 1],
    form: [
      {
        name: "business-name",
        type: "text",
        label: "Nome da empresa",
        required: true,
      },
      {
        name: "name",
        type: "text",
        label: "Seu nome",
        required: true,
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        required: true,
        validation: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
      {
        name: "phone",
        type: "tel",
        label: "WhatsApp",
        required: true,
        validation: "^\\(\\d{2}\\) \\d{5}-\\d{4}$",
      },
      {
        name: "message",
        type: "textarea",
        label: "Deixe aqui suas observações",
        required: false,
      },
    ],
  },
];
